# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-05 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211205_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 5, 17, 4, 39, 876978), verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 5, 17, 4, 39, 877946), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
