# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-13 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20211213_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 13, 17, 26, 36, 188465), verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 13, 17, 26, 36, 188465), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.FileField(blank=True, upload_to='games/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
